# Change these first
owner: Ryousuke05 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

secrets:
  - TRANSCIRCLE_STORY_BACKEND
  - TRANSCIRCLE_PASS_BACKEND
  - TRANSCIRCLE_IAM

sites:
  - name: wuxiao-web
    url: https://ciallovo.top
  - name: ciallo-api
    url: https://api.ciallovo.top
  - name: ciallo-api-bak1
    url: https://api1.ciallovo.top
  - name: transcircle.org
    url: https://transcircle.org
  - name: story.transcircle.org
    url: https://story.transcircle.org
  - name: community.transcircle.org
    url: https://community.transcircle.org
  - name: transcircle story
    url: $TRANSCIRCLE_STORY_BACKEND
  - name: transcircle pass
    url: $TRANSCIRCLE_PASS_BACKEND
  - name: transcircle iam
    url: $TRANSCIRCLE_IAM

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.ciallovo.top
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "喵喵喵喵"
  introMessage: "[项目仓库喵](https://github.com/upptime/upptime)"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: 主站
      href: https://ciallovo.top

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
